"""add_tag_tables

Revision ID: 001
Revises: 
Create Date: 2026-02-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Create tag table
    op.create_table('tag',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False, default='#8FBFB3'),
        sa.Column('created_at', sa.DateTime(timezone=False), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    
    # Create indexes for tag table
    op.create_index('idx_tag_user_id', 'tag', ['user_id'])
    op.create_index('idx_tag_name', 'tag', ['name'])
    
    # Create task_tags junction table (many-to-many)
    op.create_table('task_tags',
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=False), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('task_id', 'tag_id'),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE')
    )
    
    # Create indexes for task_tags junction table
    op.create_unique_constraint('idx_task_tags_unique', 'task_tags', ['task_id', 'tag_id'])
    op.create_index('idx_task_tags_tag_id', 'task_tags', ['tag_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Drop indexes first
    op.drop_index('idx_task_tags_tag_id', table_name='task_tags')
    op.drop_constraint('idx_task_tags_unique', 'task_tags', type_='unique')
    op.drop_index('idx_tag_name', table_name='tag')
    op.drop_index('idx_tag_user_id', table_name='tag')
    
    # Drop tables
    op.drop_table('task_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
