"""add_reminder_tables

Revision ID: 002
Revises: 001
Create Date: 2026-02-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Create task_reminder table
    op.create_table('task_reminder',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('scheduled_time', sa.DateTime(timezone=False), nullable=False),
        sa.Column('reminder_type', sa.String(length=10), nullable=False, default='in_app'),
        sa.Column('offset_minutes', sa.Integer(), nullable=False, default=-1440),
        sa.Column('status', sa.String(length=20), nullable=False, default='pending'),
        sa.Column('delivered_at', sa.DateTime(timezone=False), nullable=True),
        sa.Column('acknowledged_at', sa.DateTime(timezone=False), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, default=0),
        sa.Column('created_at', sa.DateTime(timezone=False), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE')
    )
    
    # Create indexes for task_reminder table
    op.create_index('idx_reminder_user_id', 'task_reminder', ['user_id'])
    op.create_index('idx_reminder_task_id', 'task_reminder', ['task_id'])
    op.create_index('idx_reminder_scheduled_time', 'task_reminder', ['scheduled_time'])
    op.create_index('idx_reminder_status', 'task_reminder', ['status'])
    op.create_index('idx_reminder_user_status', 'task_reminder', ['user_id', 'status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Drop indexes first
    op.drop_index('idx_reminder_user_status', table_name='task_reminder')
    op.drop_index('idx_reminder_user_status', table_name='task_reminder')
    op.drop_index('idx_reminder_status', table_name='task_reminder')
    op.drop_index('idx_reminder_scheduled_time', table_name='task_reminder')
    op.drop_index('idx_reminder_task_id', table_name='task_reminder')
    op.drop_index('idx_reminder_user_id', table_name='task_reminder')
    
    # Drop table
    op.drop_table('task_reminder')
    # ### end Alembic commands ###
