"""add_recurrence_tables

Revision ID: 003
Revises: 002
Create Date: 2026-02-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Create recurring_task_series table
    op.create_table('recurring_task_series',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.String(length=10), nullable=False, default='medium'),
        sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False, default='UTC'),
        sa.Column('paused', sa.Boolean(), nullable=False, default=False),
        sa.Column('created_at', sa.DateTime(timezone=False), nullable=False, default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=False), nullable=False, default=sa.func.now()),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='SET NULL')
    )
    
    # Create indexes for recurring_task_series table
    op.create_index('idx_recurring_series_user_id', 'recurring_task_series', ['user_id'])
    op.create_index('idx_recurring_series_start_date', 'recurring_task_series', ['start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Drop indexes first
    op.drop_index('idx_recurring_series_start_date', table_name='recurring_task_series')
    op.drop_index('idx_recurring_series_user_id', table_name='recurring_task_series')
    
    # Drop table
    op.drop_table('recurring_task_series')
    # ### end Alembic commands ###
