"""add_task_enhancements

Revision ID: 004
Revises: 003
Create Date: 2026-02-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Add new columns to existing task table
    op.add_column('task', sa.Column('reminder_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('task', sa.Column('recurrence_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('task', sa.Column('recurrence_series_id', postgresql.UUID(as_uuid=True), nullable=True))
    
    # Create index for recurrence_series_id foreign key
    op.create_index('idx_task_recurrence_series_id', 'task', ['recurrence_series_id'])
    
    # Add foreign key constraint for recurrence_series_id
    op.create_foreign_key(
        'fk_task_recurrence_series',
        'task', 'recurring_task_series',
        ['recurrence_series_id'], ['id'],
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Drop foreign key and index first
    op.drop_constraint('fk_task_recurrence_series', 'task', type_='foreignkey')
    op.drop_index('idx_task_recurrence_series_id', table_name='task')
    
    # Drop columns
    op.drop_column('task', 'recurrence_series_id')
    op.drop_column('task', 'recurrence_rule')
    op.drop_column('task', 'reminder_config')
    # ### end Alembic commands ###
