"""add_search_indexes

Revision ID: 005
Revises: 004
Create Date: 2026-02-17

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Create GIN index for full-text search on tasks table
    # Note: This uses PostgreSQL's to_tsvector for full-text search
    # Only create if tasks table exists
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'task') THEN
                CREATE INDEX IF NOT EXISTS idx_tasks_search ON task USING GIN (
                    to_tsvector('english', title || ' ' || COALESCE(description, ''))
                );
            END IF;
        END
        $$;
    """)
    
    # Create composite index for priority filtering and sorting
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'task') THEN
                CREATE INDEX IF NOT EXISTS idx_tasks_priority ON task (user_id, priority);
            END IF;
        END
        $$;
    """)
    
    # Create index for due date filtering
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'task') THEN
                CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON task (user_id, due_date);
            END IF;
        END
        $$;
    """)
    
    # Create index for status filtering
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'task') THEN
                CREATE INDEX IF NOT EXISTS idx_tasks_status ON task (user_id, status);
            END IF;
        END
        $$;
    """)
    
    # Create composite index for common filter combinations
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'task') THEN
                CREATE INDEX IF NOT EXISTS idx_tasks_filter_common ON task (user_id, status, priority, created_at);
            END IF;
        END
        $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust where ###
    # Drop indexes (only if they exist)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_indexes WHERE indexname = 'idx_tasks_filter_common') THEN
                DROP INDEX idx_tasks_filter_common;
            END IF;
        END
        $$;
    """)
    
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_indexes WHERE indexname = 'idx_tasks_status') THEN
                DROP INDEX idx_tasks_status;
            END IF;
        END
        $$;
    """)
    
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_indexes WHERE indexname = 'idx_tasks_due_date') THEN
                DROP INDEX idx_tasks_due_date;
            END IF;
        END
        $$;
    """)
    
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_indexes WHERE indexname = 'idx_tasks_priority') THEN
                DROP INDEX idx_tasks_priority;
            END IF;
        END
        $$;
    """)
    
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT FROM pg_indexes WHERE indexname = 'idx_tasks_search') THEN
                DROP INDEX idx_tasks_search;
            END IF;
        END
        $$;
    """)
    # ### end Alembic commands ###
